owner: nomi25home # Your GitHub organization or username
repo: upptime # The name of the repository where Upptime will be configured

sites:
  - name: HA
    url: https://ha.nomi25.cyou/
  - name: NC
    url: https://cloudy.nomi25.cyou/

status-website:
  #cname: custom-domain.com # Your custom domain (optional)
  baseUrl: /upptime # Optional, set if you're not using a custom domain
  logoUrl: https://example.com/logo.png
  name: Custom Upptime
  introTitle: "Custom Upptime Monitoring"
  introMessage: "This is a custom Upptime status page for monitoring various services. Powered by GitHub Actions and Upptime."
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/nomi25home/upptime
    - title: Documentation
      href: https://upptime.js.org/

# Upptime supports various notifications, alerts, and more.
